// <auto-generated />
namespace FPT_AppDev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class editTopicAndCourseBecauseLogicWrong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTopicAndCourseBecauseLogicWrong));
        
        string IMigrationMetadata.Id
        {
            get { return "202011011841056_editTopicAndCourseBecauseLogicWrong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
